language: python
services:
- postgresql
script:
- echo 0
deploy:
  provider: heroku
  api_key:
    secure: FnzqNZAFpCuVotZbof3hOaG56o3VLdPuNWnCuvF+smZGw5GQZpObcNH5e0hJPVq32geu74JWh46+RRiDn6twtcz/xJ4HHxteKfVVuoSya36fcK/Hb368rRfKn3NK2KsUev4tD9Z1BE9r5woECg9z/np7Q9qHo36up2uQ+6+vtfy3mn5J9kp6YX3JKRvaFnhXeNmY5QnTVYtHfKl6PoYBjRuNCEQIThFdERPN+0ha079qf/pMtRL/r/ZfMD/cEchgGDr5ayFDkgqLN+EMYZ+8syNL01lvHDsobai+L28NwWFNhGugCFLfGSWcnbptU5AzOR+0snIdnzdR4FWz8RifMBhRokrqLkS9nubGQJpUMUfr2FIfyuqRi7hw7pDCw77ilgayUtN8qvoxxOZmImVuoZUlO0NW/5H3UgijcTLsjLnZVq6/GxpspSEi+nIhtf9nTMJmOgMn52VTThlSLeq2J4E+9LfCqVYM2Q5r72trku6GT5Eq9p9BDyQZaTF6Nzqagp1nyXRAKcVIa4x6MAa3m3ivPKew7/DMTIiGALyeLRBovh/TcuPfcScmI4bWcQahSs49gJGrNxGKqoR0V0WUO5lVEJP/hJDnk5LNn7VsXI5EAfcdVMyQbRDFij1az1NkBLUFBP5mK9YckJ103glFnl3rrxRiAUCf/ra0TQT0qSw=
  app: bajpai
