language: python
services:
- postgresql
script:
- echo 0
deploy:
  provider: heroku
  api_key:
    secure: gv//MBIBlKt+fgRl0icDqqwZ3uR6qlt3soRAcUG6efQlpWzc5QB7sld5rBtjb0g/ryM4TXsh55hiFrCdAFb+f+huRiFM3mwSqkbF2BjCF19qb7RLQ0i9BAycd8pVqFN56elSNlKJQWozWQurBfvcohpOsM+9A7VRp6vroOuzNAAehHCXcm7gbWX+5nO8oiclhQzhP0bCE+QSgADUVt9vXcglWufL+azh/lYqmknOyIFyz+0t1Ybqlsv86SAKkK7B9bNk8KzmmBd9x3zfjx4QC3SNpa964WJwMopCgj6pXnhIf5/ePzsMwlCjmxPb6aezSMIpfXqU9Q2To4k2B2f1qtj/BWoFiDwi+GJeE8DV+RM4+OJVvPGCuS3s+d0xsnXCr4oWs8nicW9KvhM48bAz3Y+7LMkV2mnV4hx5yV3rPGeweUdYr2t9HY0M9cDm5NNqMp2PgsYh4+Ri51K3L7eXfeTHknMXCAMMOLZK1AY5BXNwt7hreVpDAVE0Yj19HyNcpfl16kvTCy/nT4KRWaRrPQtfLjZJ61uvKiy74duLRcjWKsGSs2mLG+iZNMo9PpFnwfBYWF5fE7l8+QFIy/a01yMYYILYcixk9+cxwpu4Op2EKJRLvK2SQ3RjGO+fP+nvl5gGHfen/Fyom2f6HZ3unMBQsxwoMsIJa8Cd0vZtS/8=
  app: bajpai